import Head from "next/head";
import { useRouter } from "next/router";
// components
import StartingSection from "../components/sections/starting-section";
Home.layout = "M";
export default function Home() {
  const router = useRouter();

  if (router.isFallback)
    return (
      <div>
        <h2>Loading ...</h2>
      </div>
    );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartingSection />
    </div>
  );
}
