import Head from "next/head";
// components
import StartingSection from "../components/sections/starting-section";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartingSection />
    </div>
  );
}

Home.layout = "M";
